### ISSUE TITLE
Could not find a valid gem 'jira_agile_api' (>= 0) in any repository

### ISSUE THREAD

**Issue by gglucass** [dashofcode/jira_agile_api#2]
Wanted to try out this gem because it supports some stuff jira-ruby doesn't. Did you guys stop maintaining this library and pull it? Any suggested alternatives?

**Comment by forest** [comment]
Hi @gglucass. I am not actively working on this gem, but might be picking it back up in the next few months. Our projects integration with Jira was put on hold so that is why it was never finished and published.

I would have got further but the Jira API for the Agile data is really bad. It takes quite a bit of work to conceive of a sane client interface and then implement it against the Jira APIs.

I'm happy to take pull requests if you would like to pick up some development on it.
